package com.mikstermedia.service;

import com.mikstermedia.dto.SpotifySearchResult;
import com.mikstermedia.repository.TrackRepository;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.*;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestTemplate;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.stream.Collectors;

/**
 * AI Discovery Feed Service.
 *
 * <p>Aggregates new/trending AI-generated music from multiple sources into
 * a unified "Suggested Imports" queue for admin review.
 *
 * <h2>Sources</h2>
 * <ul>
 *   <li><strong>Spotify</strong> — keyword searches for AI tool names and genre tags
 *       (suno, udio, stable audio, ai generated, etc.) across multiple queries,
 *       deduped and sorted by release date + popularity</li>
 *   <li><strong>YouTube</strong> — searches for recent AI music uploads using the
 *       YouTube Data API v3 with date ordering</li>
 *   <li><strong>Suno (song pages)</strong> — individual Suno song URLs can still be
 *       scraped for metadata; the explore/feed API is blocked (503)</li>
 * </ul>
 *
 * <h2>Why not Suno/Udio explore pages?</h2>
 * <p>Both platforms are fully client-side rendered (Next.js / React). The raw HTML
 * contains no song data — it only loads after JavaScript executes in a browser.
 * Suno's internal studio-api.suno.ai is also suspended (returns 503).
 * Individual song page scraping still works and is used in {@link SunoScraperService}.
 */
@Service
@RequiredArgsConstructor
@Slf4j
public class AiDiscoveryService {

    // ── Spotify: artist-name targeted queries ─────────────────────────────────
    // Using `artist:` prefix so Spotify matches the ARTIST field, not just any
    // word in a track title/playlist description. This dramatically reduces noise.
    private static final List<String> SPOTIFY_QUERIES = List.of(
        "artist:suno",
        "artist:udio",
        "artist:\"stable audio\"",
        "artist:\"ai generated\"",
        "artist:\"suno ai\"",
        "artist:\"udio ai\"",
        "artist:musicgen",
        "artist:\"artificial intelligence\" music",
        "artist:\"ai music\""
    );

    // ── YouTube: channel/title queries that explicitly name the AI tool used ───
    // Quoted phrases require the exact string; avoids loose matches like
    // "Santali Romantic AI Cover Song" which aren't AI-generated compositions.
    private static final List<String> YOUTUBE_QUERIES = List.of(
        "\"suno ai\" original song 2025",
        "\"udio ai\" original music 2025",
        "\"stable audio\" generated music",
        "\"ai generated\" original song 2025",
        "musicgen ai music release"
    );

    // ── AI indicator terms for post-filter ────────────────────────────────────
    // A result must match at least one ARTIST term AND/OR one TITLE term.
    private static final List<String> AI_ARTIST_TERMS = List.of(
        "suno", "udio", "stable audio", "musicgen", "ai generated",
        "artificial intelligence", "ai music", "dawnai", "cosmicai",
        "metalm ind", "ai-generated", "generative ai", "openai",
        "elevenlabs", "boomy", "aiva", "amper", "mubert", "soundraw",
        "beatoven", "soundful", "loudly", "ecrett", "melobytes"
    );

    private static final List<String> AI_TITLE_TERMS = List.of(
        "suno ai", "udio ai", "stable audio", "ai generated", "ai-generated",
        "musicgen", "made with ai", "created with ai", "ai music",
        "generated by ai", "artificial intelligence music", "ai composed",
        "ai song", "ai cover"
    );

    private static final String SPOTIFY_TOKEN_URL  = "https://accounts.spotify.com/api/token";
    private static final String SPOTIFY_SEARCH_URL = "https://api.spotify.com/v1/search";
    private static final String YT_SEARCH_URL      = "https://www.googleapis.com/youtube/v3/search";

    @Value("${spotify.client-id:}")      private String spotifyClientId;
    @Value("${spotify.client-secret:}") private String spotifyClientSecret;
    @Value("${youtube.api-key:}")        private String youtubeApiKey;

    private final TrackRepository trackRepository;
    private final ObjectMapper    objectMapper = new ObjectMapper();
    private final RestTemplate    restTemplate = new RestTemplate();

    // ── Token cache ───────────────────────────────────────────────────────────
    private String  spotifyToken     = null;
    private long    tokenExpiresAt   = 0L;

    // ── Discovery feed state ──────────────────────────────────────────────────
    private volatile boolean fetchRunning  = false;
    private volatile int     fetchProgress = 0;   // 0–100 percent
    private volatile String  fetchError    = null;
    private final List<SpotifySearchResult> lastResults = Collections.synchronizedList(new ArrayList<>());

    // ── Status ────────────────────────────────────────────────────────────────

    public Map<String, Object> getStatus() {
        Map<String, Object> s = new LinkedHashMap<>();
        s.put("running",          fetchRunning);
        s.put("progress",         fetchProgress);
        s.put("resultCount",      lastResults.size());
        if (fetchError != null) s.put("error", fetchError);
        return s;
    }

    public List<SpotifySearchResult> getLastResults() {
        return List.copyOf(lastResults);
    }

    // ── Discovery Feed Fetch ──────────────────────────────────────────────────

    /**
     * Starts an async discovery fetch across Spotify and YouTube.
     * Results replace the previous run and are available via {@link #getLastResults()}.
     */
    public void startDiscoveryFetch() {
        if (fetchRunning) {
            log.info("Discovery fetch already running, ignoring duplicate request");
            return;
        }
        fetchRunning  = true;
        fetchProgress = 0;
        fetchError    = null;
        lastResults.clear();

        Thread t = new Thread(() -> {
            try {
                List<SpotifySearchResult> combined = new ArrayList<>();

                // Collect all existing media URLs to mark already-imported items
                Set<String> importedUrls = trackRepository.findAll().stream()
                    .map(track -> track.getMediaUrl())
                    .collect(Collectors.toSet());

                // ── Phase 1: Spotify ──────────────────────────────────────────
                String token = getSpotifyToken();
                if (token != null) {
                    int total = SPOTIFY_QUERIES.size();
                    for (int i = 0; i < total; i++) {
                        String query = SPOTIFY_QUERIES.get(i);
                        try {
                            List<SpotifySearchResult> hits = searchSpotify(token, query, importedUrls);
                            // Strict AI filter — only keep genuinely AI-generated tracks
                            List<SpotifySearchResult> aiOnly = hits.stream()
                                .filter(r -> isLikelyAiGenerated(r.getArtist(), r.getTitle()))
                                .collect(Collectors.toList());
                            combined.addAll(aiOnly);
                            log.info("Spotify query '{}' → {} raw / {} passed AI filter",
                                query, hits.size(), aiOnly.size());
                        } catch (Exception e) {
                            log.warn("Spotify discovery query '{}' failed: {}", query, e.getMessage());
                        }
                        fetchProgress = (int) ((i + 1) * 50.0 / total);
                        Thread.sleep(200); // respect rate limits
                    }
                } else {
                    log.warn("AI Discovery: Spotify token unavailable — skipping Spotify phase");
                }

                // ── Phase 2: YouTube ─────────────────────────────────────────
                if (youtubeApiKey != null && !youtubeApiKey.isBlank()) {
                    int total = YOUTUBE_QUERIES.size();
                    for (int i = 0; i < total; i++) {
                        String query = YOUTUBE_QUERIES.get(i);
                        try {
                            List<SpotifySearchResult> hits = searchYouTube(query, importedUrls);
                            // Strict AI filter on YouTube results too
                            List<SpotifySearchResult> aiOnly = hits.stream()
                                .filter(r -> isLikelyAiGenerated(r.getArtist(), r.getTitle()))
                                .collect(Collectors.toList());
                            combined.addAll(aiOnly);
                            log.info("YouTube query '{}' → {} raw / {} passed AI filter",
                                query, hits.size(), aiOnly.size());
                        } catch (Exception e) {
                            log.warn("YouTube discovery query '{}' failed: {}", query, e.getMessage());
                        }
                        fetchProgress = 50 + (int) ((i + 1) * 50.0 / total);
                        Thread.sleep(200);
                    }
                } else {
                    log.warn("AI Discovery: YouTube API key unavailable — skipping YouTube phase");
                }

                // ── Deduplicate & sort ────────────────────────────────────────
                Map<String, SpotifySearchResult> deduped = new LinkedHashMap<>();
                for (SpotifySearchResult r : combined) {
                    String key = r.getSpotifyUrl() != null && !r.getSpotifyUrl().isBlank()
                        ? r.getSpotifyUrl()
                        : (r.getTitle() + "|" + r.getArtist());
                    deduped.putIfAbsent(key, r);
                }

                // Sort: not-yet-imported first, then by release date desc, then popularity desc
                List<SpotifySearchResult> sorted = deduped.values().stream()
                    .sorted(Comparator
                        .comparing(SpotifySearchResult::isAlreadyImported)
                        .thenComparing(Comparator.<SpotifySearchResult, String>comparing(
                            r -> r.getReleaseDate() != null ? r.getReleaseDate() : "").reversed())
                        .thenComparing(Comparator.comparingInt(SpotifySearchResult::getPopularity).reversed()))
                    .collect(Collectors.toList());

                lastResults.clear();
                lastResults.addAll(sorted);
                fetchProgress = 100;
                log.info("AI Discovery fetch complete: {} unique results", sorted.size());

            } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
                fetchError = "Fetch interrupted";
            } catch (Exception e) {
                fetchError = e.getMessage();
                log.error("AI Discovery fetch error: {}", e.getMessage());
            } finally {
                fetchRunning = false;
            }
        });
        t.setDaemon(true);
        t.setName("ai-discovery-fetch");
        t.start();
    }

    // ── Spotify ───────────────────────────────────────────────────────────────

    @SuppressWarnings("unchecked")
    private synchronized String getSpotifyToken() {
        if (spotifyClientId == null || spotifyClientId.isBlank()) return null;
        if (spotifyToken != null && System.currentTimeMillis() < tokenExpiresAt) return spotifyToken;
        try {
            String creds = Base64.getEncoder()
                .encodeToString((spotifyClientId + ":" + spotifyClientSecret).getBytes());
            HttpHeaders h = new HttpHeaders();
            h.set("Authorization", "Basic " + creds);
            h.setContentType(MediaType.APPLICATION_FORM_URLENCODED);
            HttpEntity<String> req = new HttpEntity<>("grant_type=client_credentials", h);
            ResponseEntity<String> resp = restTemplate.postForEntity(SPOTIFY_TOKEN_URL, req, String.class);
            JsonNode root = objectMapper.readTree(resp.getBody());
            spotifyToken   = root.get("access_token").asText();
            tokenExpiresAt = System.currentTimeMillis() + (root.get("expires_in").asLong(3600) - 120) * 1000;
            return spotifyToken;
        } catch (Exception e) {
            log.warn("Could not obtain Spotify token for AI Discovery: {}", e.getMessage());
            return null;
        }
    }

    private List<SpotifySearchResult> searchSpotify(String token, String query,
                                                      Set<String> importedUrls) throws Exception {
        String url = SPOTIFY_SEARCH_URL + "?q=" + URLEncoder.encode(query, StandardCharsets.UTF_8)
                     + "&type=track&limit=10&market=US";
        HttpHeaders h = new HttpHeaders();
        h.setBearerAuth(token);
        HttpEntity<Void> req = new HttpEntity<>(h);
        ResponseEntity<String> resp = restTemplate.exchange(url, HttpMethod.GET, req, String.class);
        JsonNode root   = objectMapper.readTree(resp.getBody());
        JsonNode items  = root.path("tracks").path("items");
        List<SpotifySearchResult> results = new ArrayList<>();
        for (JsonNode item : items) {
            try {
                String id          = item.path("id").asText("");
                String title       = item.path("name").asText("");
                String releaseDate = item.path("album").path("release_date").asText("");
                int popularity     = item.path("popularity").asInt(0);
                String spotifyUrl  = item.path("external_urls").path("spotify").asText("");
                String embedUrl    = id.isBlank() ? "" : "https://open.spotify.com/embed/track/" + id;
                String imageUrl    = "";
                JsonNode images    = item.path("album").path("images");
                if (images.isArray() && images.size() > 0) imageUrl = images.get(0).path("url").asText("");
                String artist = "";
                JsonNode artists = item.path("artists");
                if (artists.isArray()) {
                    List<String> names = new ArrayList<>();
                    artists.forEach(a -> names.add(a.path("name").asText("")));
                    artist = String.join(", ", names);
                }

                SpotifySearchResult r = new SpotifySearchResult(
                    id, title, artist,
                    item.path("album").path("name").asText(""),
                    imageUrl, spotifyUrl, embedUrl,
                    item.path("duration_ms").asInt(0), popularity
                );
                r.setReleaseDate(releaseDate);
                r.setAlreadyImported(importedUrls.contains(spotifyUrl));
                r.setPlatformSource("Spotify");
                results.add(r);
            } catch (Exception e) {
                log.trace("Skipping Spotify item: {}", e.getMessage());
            }
        }
        return results;
    }

    // ── YouTube ───────────────────────────────────────────────────────────────

    private List<SpotifySearchResult> searchYouTube(String query, Set<String> importedUrls) throws Exception {
        String url = YT_SEARCH_URL
            + "?part=snippet&type=video&videoCategoryId=10" // Music category
            + "&order=date"
            + "&q=" + URLEncoder.encode(query, StandardCharsets.UTF_8)
            + "&maxResults=10"
            + "&key=" + youtubeApiKey;
        HttpHeaders h = new HttpHeaders();
        h.setAccept(List.of(MediaType.APPLICATION_JSON));
        HttpEntity<Void> req = new HttpEntity<>(h);
        ResponseEntity<String> resp = restTemplate.exchange(url, HttpMethod.GET, req, String.class);
        JsonNode root  = objectMapper.readTree(resp.getBody());
        JsonNode items = root.path("items");
        List<SpotifySearchResult> results = new ArrayList<>();
        for (JsonNode item : items) {
            try {
                String videoId    = item.path("id").path("videoId").asText("");
                if (videoId.isBlank()) continue;
                String title      = item.path("snippet").path("title").asText("");
                String channel    = item.path("snippet").path("channelTitle").asText("");
                String published  = item.path("snippet").path("publishedAt").asText("");
                String thumbUrl   = item.path("snippet").path("thumbnails").path("high").path("url").asText("");
                String watchUrl   = "https://www.youtube.com/watch?v=" + videoId;
                String embedUrl   = "https://www.youtube.com/embed/" + videoId;
                // Use release date as just the date portion of the ISO timestamp
                String releaseDate = published.length() >= 10 ? published.substring(0, 10) : published;

                SpotifySearchResult r = new SpotifySearchResult(
                    "yt-" + videoId, title, channel, "", thumbUrl,
                    watchUrl, embedUrl, 0, 0
                );
                r.setReleaseDate(releaseDate);
                r.setPublishedAt(published);
                r.setAlreadyImported(importedUrls.contains(watchUrl) || importedUrls.contains(embedUrl));
                r.setPlatformSource("YouTube");
                results.add(r);
            } catch (Exception e) {
                log.trace("Skipping YouTube item: {}", e.getMessage());
            }
        }
        return results;
    }

    // ── AI generation filter ───────────────────────────────────────────────────

    /**
     * Returns {@code true} only if the track is very likely to be AI-generated.
     *
     * <p>Checks are case-insensitive substring matches against two lists:
     * <ul>
     *   <li>{@code AI_ARTIST_TERMS} — artist name contains a known AI tool/platform</li>
     *   <li>{@code AI_TITLE_TERMS}  — track title contains a specific AI phrase</li>
     * </ul>
     *
     * <p>A match on EITHER list is sufficient to pass, but single-word tokens like
     * bare "ai" are intentionally absent from the title list to avoid false positives
     * (e.g. "Jai" or "Taiwan" both contain the letters "ai").
     */
    private boolean isLikelyAiGenerated(String artist, String title) {
        String artistLower = artist  != null ? artist.toLowerCase()  : "";
        String titleLower  = title   != null ? title.toLowerCase()   : "";

        // Check artist name against known AI tool names
        for (String term : AI_ARTIST_TERMS) {
            if (artistLower.contains(term)) {
                log.debug("AI filter PASS (artist match '{}') — {}", term, artist);
                return true;
            }
        }

        // Check title against specific multi-word AI phrases
        for (String term : AI_TITLE_TERMS) {
            if (titleLower.contains(term)) {
                log.debug("AI filter PASS (title match '{}') — {}", term, title);
                return true;
            }
        }

        log.debug("AI filter REJECT — artist='{}', title='{}'", artist, title);
        return false;
    }
}
